# Generated by Django 3.2 on 2022-02-07 14:13

from django.db import migrations


def create_threads(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Message = apps.get_model("dialogs", "Message")
    Thread = apps.get_model("dialogs", "Thread")
    user1 = User.objects.create(username="Oleg", email="a@gmail.com")
    user2 = User.objects.create(username="abc", email="ab56@ex.com")
    thread = Thread.objects.create()
    thread.participants.add(user1, user2)
    Message.objects.bulk_create(
        [
            Message(text="Django 1.0 Released", thread=thread, sender=user1),
            Message(text="Hello. How are you?", thread=thread, sender=user1, is_read=True),
            Message(text="124235543534", thread=thread, sender=user2),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("dialogs", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_threads),
    ]
