# Generated by Django 3.2 on 2022-09-04 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dialogs', '0002_auto_20220207_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='participants',
            field=models.ManyToManyField(related_name='user_thread', to=settings.AUTH_USER_MODEL),
        ),
    ]
